### ISSUE TITLE
Upload easypost jar to Maven Central

### ISSUE THREAD

**Issue by keeth** [EasyPost/easypost-java#1]
Would make it easier to use.  Thanks!

**Comment by munnja001** [comment]
+1

**Comment by 9992800** [comment]
Hello, When I import this to eclipse , It shows some package errors. When I fixed the errors, How to build a jar file from source code, Thanks Very much!
By the way I build a jar file using "mvn package" and then copy the jar file to my libs directory of my eclipse project, but When I used it , It always show me the error:"Could not connect to EasyPost(https://api.easypost.com/v2). Please check your internet connection and try again....
But I am sure I can visit this link by the browser of my android device.Looking forward your response. Thanks very much.

**Comment by jitpack-io** [comment]
Hi! Would be really easy to publish on https://jitpack.io

**Comment by att14** [comment]
This is on the backlog, I'll look into it as soon as possible.

**Comment by sbailliez** [comment]
Any progress on this ?

**Comment by SireInsectus** [comment]
+1, we can help with this if you like...

**Comment by att14** [comment]
I looked into this a bit, but we have no experience with Maven. Can you point us to a good walkthrough?

**Comment by SireInsectus** [comment]
Sure... It's first going to depend on what type of build system you use:
Maven, Ant, Gradle, etc..

On Mon, Jan 4, 2016 at 1:29 PM Andrew Tribone <notifications@github.com>
wrote:

> I looked into this a bit, but we have no experience with Maven. Can you
> point us to a good walkthrough?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EasyPost/easypost-java/issues/1#issuecomment-168815481>
> .
>
-- 
Jacob D. Parr
559-640-PARR
me@jacobparr.com
http://www.jacobparr.com

**Comment by att14** [comment]
Maven

**Comment by SireInsectus** [comment]
A company called SonaType plays the middle man... The landing page your
will be interested in is http://central.sonatype.org. Their published guide
is here: http://central.sonatype.org/pages/ossrh-guide.html.

Your first step will be to create an account with SonaType which is really
just a Jira account (see guide) and then send a ticket requesting a
specific repo - I think they just need your group name - I'm guessing that
would be *com.easypost*. Then wait two days.

You will eventually need to figure out what your fully qualified group name
is along with the artifact name. You can change it later, but you really
don't want to change it, ever.

Your POM is currently using *com.easypost*:*easypost-java*, but I would
suggest the group ID *com.easypost.shipping* following the pattern of
com.domain.appname.

Because the artifact name is conventionally the same as the jar file name
you will want to repeat the company and appname in some form. Some examples
being:

   - *com.easypost.shipping*:*easypost-shipping-client*
   -
*com.easypost.shipping:ep-shipping-client *
   -
*com.easypost.shipping:ep-ship-client *

I personally like the first, *com.easypost.shipping*:*easypost-shipping-client
*from which I would get the jar *easypost-shipping-client-1.0.0.jar*

I'm currently using Gradle for my build, but I have the XML configuration
you will need for Maven on another machine at home. I'll try to chase it
down for you tonight.

Feel free to give me a call if you like. I'll also be in SF the first week
of February for whatever it's worth.

On Wed, Jan 6, 2016 at 9:58 AM Andrew Tribone <notifications@github.com>
wrote:

> Maven
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EasyPost/easypost-java/issues/1#issuecomment-169404609>
> .
>
-- 
Jacob D. Parr
559-640-PARR
me@jacobparr.com
http://www.jacobparr.com

**Comment by SireInsectus** [comment]
I wasn't able to find my old maven examples - apparently I converted to
Gradle earlier than I thought. I have a call out to a collaborator to see
if he has a copy but I'm don't think he would.

Before I put the energy into digging up the examples, let me know. I don't
want to put the energy into it until you guys want to or are ready to move
forward.


On Wed, Jan 6, 2016 at 10:26 AM Jacob D Parr <me@jacobparr.com> wrote:

> A company called SonaType plays the middle man... The landing page your
> will be interested in is http://central.sonatype.org. Their published
> guide is here: http://central.sonatype.org/pages/ossrh-guide.html.
>
> Your first step will be to create an account with SonaType which is really
> just a Jira account (see guide) and then send a ticket requesting a
> specific repo - I think they just need your group name - I'm guessing that
> would be *com.easypost*. Then wait two days.
>
> You will eventually need to figure out what your fully qualified group
> name is along with the artifact name. You can change it later, but you
> really don't want to change it, ever.
>
> Your POM is currently using *com.easypost*:*easypost-java*, but I would
> suggest the group ID *com.easypost.shipping* following the pattern of
> com.domain.appname.
>
> Because the artifact name is conventionally the same as the jar file name
> you will want to repeat the company and appname in some form. Some examples
> being:
>
>    - *com.easypost.shipping*:*easypost-shipping-client*
>    -
> *com.easypost.shipping:ep-shipping-client *
>    -
> *com.easypost.shipping:ep-ship-client *
>
> I personally like the first, *com.easypost.shipping*:*easypost-shipping-client
> *from which I would get the jar *easypost-shipping-client-1.0.0.jar*
>
> I'm currently using Gradle for my build, but I have the XML configuration
> you will need for Maven on another machine at home. I'll try to chase it
> down for you tonight.
>
> Feel free to give me a call if you like. I'll also be in SF the first week
> of February for whatever it's worth.
>
> On Wed, Jan 6, 2016 at 9:58 AM Andrew Tribone <notifications@github.com>
> wrote:
>
>> Maven
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/EasyPost/easypost-java/issues/1#issuecomment-169404609>
>> .
>>
> --
> Jacob D. Parr
> 559-640-PARR
> me@jacobparr.com
> http://www.jacobparr.com
>
-- 
Jacob D. Parr
559-640-PARR
me@jacobparr.com
http://www.jacobparr.com

**Comment by imightbeamy** [comment]
Any more progress? Would love for this to happen!

**Comment by SireInsectus** [comment]
I don't have a Maven example anymore, we are now using Gradle. However, the
guide published by Sonatype is really easy to follow:

The landing page your will be interested in is http://central.sonatype.org.
Their published guide is here:
http://central.sonatype.org/pages/ossrh-guide.html.

On Mon, Mar 28, 2016 at 8:34 AM Amy Ciavolino <notifications@github.com>
wrote:

> Any more progress? Would love for this to happen!
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/EasyPost/easypost-java/issues/1#issuecomment-202442069>
>
-- 
Jacob D. Parr
559-640-PARR
me@jacobparr.com
http://www.jacobparr.com

**Comment by imightbeamy** [comment]
If anyone finds this and is still looking for a solution I was able to use @jitpack-io even though this repo doesn't have a release. It was super simple for me in sbt:
```sbt
resolvers += "jitpack" at "https://jitpack.io"
libraryDependencies += "com.github.EasyPost" % "easypost-java" % "c3150850ee61021906e95e3efa46a70cae23ca3f"
```
The end can be any commit hash.

**Comment by blairmotchan** [comment]
I use @jitpack-io as well, but it would be nice to have an actual version in a repository so that I'm not stuck with using commit hashes and wondering if the somewhat arbitrary hash I've chosen is stable.  

EasyPost is a paid for service, and this issue is almost 2 years old... What is the hesitancy to commit to creating a better versioned library?  What do we need to do to get more traction on this?

At the least, could you start tagging and creating releases so we don't have to use a commit hash in jitpack?

EasyPost has been great:  I like working with the API and really appreciate the fact that there is an actively developed java client.  I just don't understand why this issue has languished.

**Comment by victoryftw** [comment]
Sorry for the delays on this; we've finally uploaded the "easypost-api-client" to Maven!

**Comment by SireInsectus** [comment]
Awesome!

On Wed, Jun 22, 2016 at 12:46 PM Jake Epstein <notifications@github.com>
wrote:

> Sorry for the delays on this; we've finally uploaded the
> "easypost-api-client" to Maven!
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/EasyPost/easypost-java/issues/1#issuecomment-227855610>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AECgJq1D1EzL60g8skDQuAB8_nxC0a2Lks5qOZD_gaJpZM4CVR4y>
> .
>
-- 
Jacob D. Parr
559-640-PARR
me@jacobparr.com
http://www.jacobparr.com
