### ISSUE TITLE
[Feat]: Delete Tracker

### ISSUE THREAD

**Issue by yasnmert** [EasyPost/easypost-java#261]
### Feature Request Is New

- [X] I have verified that the requested feature does not already exist or has not already been requested.

### Description of the feature

We must remove the trackers we generated for the distributed transaction, but unfortunately, there doesn't seem to be an API available for deleting trackers according to the documentation. Would it be possible to request an enhancement for this feature?

**Comment by Justintime50** [comment]
Hey @yasnmert, thanks for submitting this feature request. Since this is an API feature and not a library feature, we'd like to refer you to our support team to submit that so it gets in front of the right people. They can be reached at support@easypost.com. If they implement something like this, we can then add it to each of the client libraries.
