### ISSUE TITLE
How should I install the jar into my maven project?

### ISSUE THREAD

**Issue by shiweili77** [EasyPost/easypost-java#37]
I remember before I download a .jar file
and do 
mvn install:install-file -Dfile=<path>/easypost-java-2.1.4.jar -DgroupId=com.easypost -DartifactId=easypost-java -Dversion=2.1.4 -Dpackaging=jar

But now seems I can find no where to download the .jar, so tried to build one from the git project.
But while building it seems there are a lot of compilation errors.

**Comment by shiweili77** [comment]
Something like 
[ERROR] /Users/shiweili/Downloads/easypost-java-master/src/test/java/com/easypost/EasyPostTest.java:[460,34] cannot find symbol
  symbol:   method containsString(java.lang.String)
  location: class com.easypost.EasyPostTest

**Comment by shiweili77** [comment]
The context is
I want to use the "verifications" in Address object.
But seems the one I got 2.1.4 does not have one....

**Comment by victoryftw** [comment]
Hi shiweili77,

Thanks for bringing this to our attention.

At this time, we are not aware of any compilation issues in the newest version of our client library. Since I can confirm that we have several working compilations of this client library, these errors suggest that there may be a versioning/dependency issue at play here. Can you confirm you are using the newest version of the client library (currently on 3.3.5) with an up-to-date version of Java (I have a working install with Java 1.8.0_66), as well as the appropriate versions of our dependancies (currently GSON 2.7, JUnit 4.10 and Hamcrest-Core 1.3)?

Thanks,
Jake

**Comment by shiweili77** [comment]
I removed <scope>test</scope> from the above decencies in the pom, looks it is working now.
Thanks!
