### ISSUE TITLE
com.easypost.model.Error does not have a code field

### ISSUE THREAD

**Issue by shiweili77** [EasyPost/easypost-java#38]
I am using the Address verification feature and found, according to curl response.
The verification:delivery:errors object has code, field, message fields.
But in the com.easypost.model.Error object, seems only have field and message. And it looks like code is being set in field. 

Is my understanding correct?

**Comment by Justintime50** [comment]
Can you elaborate on where you are referencing? If it's the Error model, the code field is [mapped and used](https://github.com/EasyPost/easypost-java/blob/master/src/main/java/com/easypost/model/Error.java#L7), otherwise some additional context would be helpful in knowing what may be missing here. Thanks!

**Comment by Justintime50** [comment]
@shiweili77 can you clarify your request above based on my last comment?

**Comment by Justintime50** [comment]
After checking again, it looks like the `code` field was added after this was initially submitted. Please use the most recent version of this library to ensure this fix is available to you and you should be all set.
